# Generated by Django 4.2.19 on 2025-02-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
